services:
  - type: web
    name: pdf-ocr-api
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements-api.txt
    startCommand: uvicorn fastapi_app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /

  - type: web
    name: pdf-ocr-app
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements-app.txt
    startCommand: streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: FASTAPI_URL
        value: https://pdf-ocr-api-bl6u.onrender.com
      - key: HF_OCR_URL
        value: https://huggingface.co/spaces/kangjinmo/easyocr-ko-en
